# Generated by Django 5.1 on 2024-10-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passengers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengers',
            old_name='second',
            new_name='last',
        ),
    ]
